### PR TITLE
teminal: option to log errors and service messages to file, closes #1516

### LINKED ISSUE #1516: [CLI] Please write errors to stderr
SimpleX for CLI has a habbit of writing a lot of errors messages, that can make if difficult to see what happened earlier in a conversation. To mitigate that I have, for a while, been launching SimpleX like this:

```sh
$ exec simplex-chat 2>/dev/null
```

However, I still see errors like these written to stdout:

```
server disconnected smpN.[…]
> exception: HandshakeFailed (Error_Misc "Network.Socket.[…]
server connected smpN.[…]
```

It would be nice to either have _all_ error messages written to stderr, or to be able to configure the loglevel manually.

This is:

*  **simplex-chat-ubuntu-20_04-x86-64**: v4.3.0

Cheers.

### PR DESCRIPTION
**Pull request by epoberezkin**

### CODE REVIEW

File: src/Simplex/Chat/Terminal/Output.hs [hunk 1]
```diff
@@ -91,30 +92,36 @@ withTermLock ChatTerminal {termLock} action = do
...
           void $ runReaderT (runExceptT $ processChatCommand (APIChatRead chatRef (Just (itemId, itemId)))) cc
         _ -> pure ()
+    logResponse path s = withFile path AppendMode $ \h -> mapM_ (hPutStrLn h . unStyle) s
 
 printRespToTerminal :: ChatTerminal -> ChatController -> Bool -> ChatResponse -> IO ()
-printRespToTerminal ct cc liveItems r = do
+printRespToTerminal ct cc liveItems r = reponseString cc liveItems r >>= printToTerminal ct
+
+reponseString :: ChatController -> Bool -> ChatResponse -> IO [StyledString]
+reponseString cc liveItems r = do
```
Comment (spaced4ndy) [inline src/Simplex/Chat/Terminal/Output.hs:121]:
```suggestion
responseString :: ChatController -> Bool -> ChatResponse -> IO [StyledString]
responseString cc liveItems r = do
```

File: src/Simplex/Chat/Terminal/Output.hs [hunk 2]
```diff
@@ -91,30 +92,36 @@ withTermLock ChatTerminal {termLock} action = do
...
     case r of
       CRNewChatItem _ ci -> markChatItemRead ci
       CRChatItemUpdated _ ci -> markChatItemRead ci
       _ -> pure ()
+    let printResp = case logFilePath of
+          Just path -> if logResponseToFile r then logResponse path else printToTerminal ct
+          _ -> printToTerminal ct
     liveItems <- readTVarIO showLiveItems
-    printRespToTerminal ct cc liveItems r
+    reponseString cc liveItems r >>= printResp
```
Comment (spaced4ndy) [inline src/Simplex/Chat/Terminal/Output.hs:106]:
```suggestion
    responseString cc liveItems r >>= printResp
```

**Review by spaced4ndy — DISMISSED** [review]
