### PR TITLE
core: fix `/_groups` command

### LINKED ISSUE #5195: [Bug]: `/_groups` command doesn't work
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Linux, Mac, Windows

### OS version

all

### App version

6.1.1.0

### Current Behavior

I faced the issue when I try to implement feature `list groups` in sdk  #5186 , and I got the error message like that `'Failed reading: empty'`.

### Expected Behavior

return the groups

### Steps To Reproduce

1. make sure create a user which `userId` is `1` 
2. create some groups for user
3. send the command `/_groups 1`

### Relevant log output

```shell
1. sdk output `commandErr: 'Failed reading: empty'`
2. cli output nothing even I set `-l debug`.
```

### PR DESCRIPTION
**Pull request by ed-asriyan**
add missing space after `/_groups`. fixes #5195

### CODE REVIEW

File: src/Simplex/Chat/Library/Commands.hs [hunk 1]
```diff
@@ -4526,8 +4526,8 @@ chatCommandP =
       "/clear " *> char_ '@' *> (ClearContact <$> displayNameP),
       ("/members " <|> "/ms ") *> char_ '#' *> (ListMembers <$> displayNameP),
       "/member support chats #" *> (ListMemberSupportChats <$> displayNameP),
-      "/_groups" *> (APIListGroups <$> A.decimal <*> optional (" @" *> A.decimal) <*> optional (A.space *> textP)),
-      ("/groups" <|> "/gs") *> (ListGroups <$> optional (" @" *> displayNameP) <*> optional (A.space *> textP)),
+      "/_groups " *> (APIListGroups <$> A.decimal <*> optional (" @" *> A.decimal) <*> optional (A.space *> textP)),
+      ("/groups " <|> "/gs ") *> (ListGroups <$> optional (" @" *> displayNameP) <*> optional (A.space *> textP)),
```
Comment (epoberezkin) [inline src/Simplex/Chat/Library/Commands.hs]:
```suggestion
      ("/groups" <|> "/gs") *> (ListGroups <$> optional (" @" *> displayNameP) <*> optional (A.space *> textP)),
```
